tag_list = {
    "title": [
        "software engineer",
        "software developer",
        "web developer",
        "web designer",
        "data analyst",
        "data scientist",
        "data engineer",
        "database administrator",
        "business analyst",
        "systems analyst",
        "network engineer",
        "security analyst",
        "security engineer",
        "security architect",
        "security consultant",
        "security specialist",
        "security administrator",
        "security manager",
        "security director",
        "security officer",
        "security auditor",
        "security analyst",
        "devops engineer",
        "cloud engineer",
        "cloud architect",
        "cloud consultant",
        "cloud specialist",
        "cloud administrator",
        "cloud manager",
        "cloud director",
        "cloud officer",
        "devops"
        "full stack developer",
        "front end developer",
        "back end developer",
        "mobile developer",
        "ios developer",
        "android developer",
    ],
    "language": [
        "python",
        "java",
        "javascript",
        "c",
        "c++",
        "c#",
        "php",
        "ruby",
        "swift",
        "kotlin",
        "objective-c",
        "typescript",
        "scala",
        "r",
        "go",
        "rust",
        "perl",
        "shell",
        "bash",
        "powershell",
        "html",
        "css",
        "sql",
        "nosql",
        "graphql",
        "xml",
        "json",
        "yaml",
        "markdown",
        "latex",
        "assembly",
        "fortran",
        "cobol",
        "ada",
        "lisp",
        "scheme",
        "prolog",
        "smalltalk",
        "haskell",
        "erlang",
        "elixir",
        "clojure",
        "f#",
        "ocaml",
        "lua",
        "dart",
        "racket",
        "julia",
        "coffeescript",
        "typescript",
        "elm",
        "purescript",
        "reasonml",
    ],
    "framework": [
        "django",
        "flask",
        "fastapi",
        "tornado",
        "pyramid",
        "rails",
        "sinatra",
        "express",
        "koa",
        "meteor",
        "next.js",
        "nuxt.js",
        "vue",
        "react",
        "angular",
        "svelte",
        "ember",
        "backbone",
        "laravel",
        "symfony",
        "zend",
        "codeigniter",
        "cakephp",
        "yii",
        "spring",
        "struts",
        "hibernate",
        "jsf",
        "gwt",
        "play",
        "grails",
        "dropwizard",
        "spark",
        "jhipster",
        "quarkus",
        "micronaut",
        "node.js",
    ],
    "database": [
        "mysql",
        "mariadb",
        "postgresql",
        "sqlite",
        "oracle",
        "mssql",
        "mongodb",
        "cassandra",
        "couchdb",
        "redis",
        "memcached",
        "elasticsearch",
        "influxdb",
        "neo4j",
        "arangodb",
        "orientdb",
        "hbase",
        "couchbase",
        "dynamodb",
        "cosmosdb",
        "bigtable",
        "bigquery",
        "redshift",
        "snowflake",
        "teradata",
        "db2",
        "sybase",
        "informix",
        "firebird",
        "interbase",
        "sqlserver",
    ],
    "tool": [
        "git",
        "svn",
        "mercurial",
        "docker",
        "kubernetes",
        "vagrant",
        "ansible",
        "puppet",
        "chef",
        "saltstack",
        "jenkins",
        "travis",
        "circleci",
        "github",
        "gitlab",
        "bitbucket",
        "jira",
        "confluence",
        "slack",
        "teams",
        "zoom",
        "webex",
        "skype",
    ],
    "os": [
        "windows",
        "linux",
        "android",
        "ios",
        "macos",
        "unix",
        "freebsd",
        "openbsd",
        "netbsd",
        "solaris",
        "aix",
    ],
    "cloud": [
        "aws",
        "azure",
        "gcp",
        "ibmcloud",
        "oraclecloud",
        "alibabacloud",
        "tencentcloud",
        "baiduyun",
        "qiniu",
        "upyun",
    ],
    "other": [
        "agile",
        "scrum",
        "kanban",
        "devops",
        "ci",
        "cd",
        "tdd",
        "bdd",
        "ddd",
        "microservices",
        "soa",
        "rest",
        "soap",
        "graphql",
        "oauth",
        "openid",
        "jwt",
        "oauth2",
        "openidconnect",
    ]
}
